// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovelManagementApi.src.model.db;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NovelManagementApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NovelManagementApi.src.model.db.NovelContentsEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar")
                        .HasColumnName("id");

                    b.Property<string>("ChapterName")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("chapter_name");

                    b.Property<string>("Contents")
                        .HasColumnType("text")
                        .HasColumnName("contents");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int4")
                        .HasColumnName("display_order");

                    b.Property<string>("NovelId")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("novel_id");

                    b.Property<string>("OwnerUserAccountId")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("owner_user_account_id");

                    b.Property<string>("ParentContentsId")
                        .HasColumnType("varchar")
                        .HasColumnName("parent_contents_id");

                    b.HasKey("Id");

                    b.HasIndex("NovelId");

                    b.HasIndex("OwnerUserAccountId");

                    b.ToTable("novel_contents");
                });

            modelBuilder.Entity("NovelManagementApi.src.model.db.NovelEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("OwnerUserAccountId")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("owner_user_account_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserAccountId");

                    b.ToTable("novels");
                });

            modelBuilder.Entity("NovelManagementApi.src.model.db.NovelSettingEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("Attributes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("attributes");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int4")
                        .HasColumnName("display_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.Property<string>("NovelId")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("novel_id");

                    b.Property<string>("OwnerUserAccountId")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("owner_user_account_id");

                    b.Property<string>("ParentSettingId")
                        .HasColumnType("varchar")
                        .HasColumnName("parent_setting_id");

                    b.HasKey("Id");

                    b.HasIndex("NovelId");

                    b.HasIndex("OwnerUserAccountId");

                    b.ToTable("novel_settings");
                });

            modelBuilder.Entity("NovelManagementApi.src.model.db.PromptTemplateEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int4")
                        .HasColumnName("display_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.Property<string>("OwnerUserAccountId")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("owner_user_account_id");

                    b.Property<string>("Template")
                        .HasColumnType("text")
                        .HasColumnName("template");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserAccountId");

                    b.ToTable("prompt_templates");
                });

            modelBuilder.Entity("NovelManagementApi.src.model.db.UserAccountEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Gmail")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("gmail");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("varchar")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.Property<string>("UserSettingId")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("user_setting_id");

                    b.HasKey("Id");

                    b.HasIndex("Gmail")
                        .IsUnique();

                    b.HasIndex("UserSettingId");

                    b.ToTable("user_accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
